# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [5]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv) and assign it to a variable called chipo.

In [9]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep="\t")
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [10]:
chipo["item_price"] = chipo["item_price"].str.strip("$ ").astype(float)

### Step 3. Name of the max valued product

In [11]:
chipo.loc[chipo["item_price"].idxmax(), "item_name"]

'Chips and Fresh Tomato Salsa'

### Step 4. How many products cost more than $10.00?

In [ ]:
(chipo["item_price"] > 10).sum()

### Step 4.1: Y cuántos pedidos se han hecho con un producto de más de 10$? Es lo mismo?

In [12]:
chipo[chipo["item_price"] > 10]["order_id"].nunique()

863

### Step 4.2: Y cuántos pedidos se han hecho de más de 10$? Es lo mismo?

In [13]:
total_pedido = chipo.groupby("order_id")["item_price"].sum()
(total_pedido > 10).sum()

np.int64(1834)

### Step 4.3: Y en cuántos pedidos se ha pagado más de 10$ por un mismo producto? Es lo mismo?

In [14]:
por_producto = chipo.groupby(["order_id", "item_name"])["item_price"].sum()
por_producto[por_producto > 10].index.get_level_values("order_id").nunique()

945

### Step 5. What is the price of each item and name it unit_price. Get only item_name and unit_price

In [15]:
chipo["unit_price"] = chipo["item_price"] / chipo["quantity"]
precios = chipo[["item_name", "unit_price"]]
precios

                                  item_name  unit_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl        8.49
...                                     ...         ...
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]

### Step 6. Sort by the name of the item

In [16]:
chipo.sort_values("item_name")

,order_id,quantity,item_name,choice_description,item_price,unit_price
298,129,1,6 Pack Soft Drink,[Sprite],6.49,6.49
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
357,154,1,6 Pack Soft Drink,[Coke],6.49,6.49
388,168,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
417,182,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
...,...,...,...,...,...,...
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49,8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75,8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49,8.49
3889,1559,2,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",16.98,8.49

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

In [ ]:
chipo.loc[chipo["unit_price"].idxmax(), "quantity"]

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [17]:
(chipo["item_name"] == "Veggie Salad Bowl").sum()

np.int64(18)

### Step 9. How many times did someone order more than one Canned Soda?

In [18]:
((chipo["item_name"] == "Canned Soda") & (chipo["quantity"] > 1)).sum()

np.int64(20)